package selenium_study;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class Whatssapp {

	public static void main(String[] args) throws InterruptedException {
		
		//here we are going to inspect whatsapp
		
		
		System.setProperty("webdriver.chrome.driver", "C:\\Program Files\\Java\\selenium\\chromedriver_win32\\chromedriver.exe");
		WebDriver d = new ChromeDriver();
		d.get("https://web.whatsapp.com/");
		Thread.sleep(5000);
		
		d.findElement(By.xpath("//div[@title='Type a message']")).sendKeys("this is msg generated by selenium using inspect");
	}

}
